# Usar una imagen de Python
FROM python:3.9

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos necesarios
COPY . .

# Instalar las dependencias
RUN pip install grpcio grpcio-tools kafka-python

# Ejecutar el servidor
CMD ["python", "server.py"]
